# Generated by Django 5.0.2 on 2025-07-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deepseek_Demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepseekapikey',
            name='user',
        ),
    ]
